[project]
name = "git-stalker"
version = "0.1.0"
description = "Track GitHub activity for a user within an organization"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests",
    "python-dotenv",
    "rich",
    "typer"
]
